tasks:
  - init: |
      mkdir tutorial
      cd tutorial
      mkdir tutorial 
      cp /workspace/data-prepper/examples/log-ingestion/index.html  /workspace/data-prepper/tutorial/index.html
      cp /workspace/data-prepper/docs/images/Log_Ingestion_FluentBit_DataPrepper_OpenSearch.jpg /workspace/data-prepper/tutorial/Log_Ingestion_FluentBit_DataPrepper_OpenSearch.jpg
      cp /workspace/data-prepper/examples/log-ingestion/log_pipeline.yaml  /workspace/data-prepper/tutorial/log_pipeline.txt
      python3 -m http.server 8000
    
  - init: "cd ./examples/log-ingestion && docker-compose pull"
  - command: "cd ./examples/log-ingestion && docker-compose up"
  - init: |
      ./gradlew clean :release:docker:docker -Prelease
      gp await-port 9200
    command: |
      touch ./tutorial/tutorial/data-prepper-built.txt
      docker run --name data-prepper -v /workspace/data-prepper/examples/log-ingestion/log_pipeline.yaml:/usr/share/data-prepper/pipelines.yaml --network "log-ingestion_opensearch-net" opensearch-data-prepper:1.2.0-SNAPSHOT
  - init: |
      gp await-port 5601
      ./check-dashboards.sh
      curl -u admin:admin -XPOST http://localhost:5601/api/saved_objects/index-pattern/  -H 'osd-xsrf: true' -H 'Content-Type: application/json' -d "$(cat ./examples/log-ingestion/index-pattern.json)"
    command: "touch ./tutorial/tutorial/dashboardsready.txt"
  - init: |
      touch /workspace/data-prepper/examples/log-ingestion/test.log
      gp await-port 9200
      go get -u github.com/mingrammer/flog
    command: |
      ./check-data-prepper.sh
      curl -XPUT https://localhost:9200/_index_template/apache_logs_template -u admin:admin -k -H 'Content-Type: application/json' -d "$(cat ./examples/log-ingestion/template.json)"
      flog -d 2s -l -t log -o /workspace/data-prepper/examples/log-ingestion/test.log -w

ports:
  - port: 1234
    onOpen: ignore
  - port: 4900
    onOpen: ignore
  - port: 2021
    onOpen: ignore
  - port: 8000
    onOpen: open-preview
  - port: 5601
    onOpen: ignore
  - port: 2021
    onOpen: ignore
  - port: 9600
    onOpen: ignore
  - port: 5678
    onOpen: ignore
  - port: 14250
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 21890
    onOpen: ignore
  - port: 5778
    onOpen: ignore
  