tasks:
  - init: |
      mkdir tutorial
      cd tutorial
      mkdir tutorial 
#  - init: "mkdir tutorial && curl https://opensearch.org/tutorials/data-prepper-jaeger.html > ./tutorial/index.html && cd tutorial && python3 -m http.server 8000"
  - init: "cd ./examples/log-ingestion && docker-compose pull"
  - command: "cd ./examples/log-ingestion && docker-compose up"
  - init: |
      ./gradlew clean :release:docker:docker -Prelease
      gp await-port 9200
    command: |
      touch ./tutorial/tutorial/data-prepper-built.txt
      docker run --name data-prepper -v /workspace/data-prepper/examples/log-ingestion/log_pipeline.yaml:/usr/share/data-prepper/pipelines.yaml --network "log-ingestion_opensearch-net" opensearch-data-prepper:1.2.0-SNAPSHOT
  - init: |
      gp await-port 5601
      ./check-dashboards.sh
    command: "touch ./tutorial/tutorial/dashboardsready.txt"
  - init: |
      go get -u github.com/mingrammer/flog
    command: |
      ./check-data-prepper.sh
      flog -d 2s -l -t log -o /workspace/data-prepper/examples/log-ingestion/test.log -w

ports:
  - port: 4900
    onOpen: ignore
  - port: 2021
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 5601
    onOpen: ignore
  - port: 2021
    onOpen: ignore
  - port: 9600
    onOpen: ignore
  - port: 5678
    onOpen: ignore
  - port: 14250
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 21890
    onOpen: ignore
  - port: 5778
    onOpen: ignore
  