tasks:
  - init: "cd ./examples/jaeger-hotrod && docker-compose pull"
  - command: "cd ./examples/jaeger-hotrod && docker-compose up"
  - init: "./check-dashboards.sh"
    command: "gp preview $(gp url 5601)"

ports:
  - port: 5601
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
  - port: 9600
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
  - port: 8083
    onOpen: ignore
  - port: 14250
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 21890
    onOpen: ignore
  - port: 5778
    onOpen: ignore
  